version: '3'
services:
  backend:
    build:
      context: ./src
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: clinique
