# Generated by Django 4.2.3 on 2023-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=10)),
                ('age', models.IntegerField()),
                ('childish_diseases', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('accident_or_serious_trauma', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('surgical_intervention', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('high_fevers_last_year', models.CharField(choices=[('more_than_3_months_ago', 'More than 3 months ago'), ('less_than_3_months_ago', 'Less than 3 months ago'), ('no', 'No')], max_length=30)),
                ('alcohol_consumption', models.CharField(choices=[('once_a_week', 'Once a week'), ('hardly_ever_or_never', 'Hardly ever or never'), ('several_times_a_week', 'Several times a week'), ('several_times_a_day', 'Several times a day'), ('every_day', 'Every day')], max_length=30)),
                ('smoking_habit', models.CharField(choices=[('occasional', 'Occasional'), ('daily', 'Daily'), ('never', 'Never')], max_length=10)),
                ('hours_sitting_per_day', models.IntegerField()),
                ('diagnosis', models.CharField(max_length=10)),
            ],
        ),
    ]
